### ISSUE TITLE
【提醒】协议问题

### ISSUE THREAD

**Issue by sandtechnology** [chesterccj305/Mods-zh_tw-Lang-Pack#1]
舞秋风大大你好，首先感谢你的贡献，但是这里有一个比较重要的协议问题：
这个繁体中文包是基于[简体中文包](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package)的
而简体中文包使用了CC协议（[全文](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh)）：

> 本作品采用 知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议（简体中文）进行许可，协议全文可在此找到。

需要遵守的内容：
>     署名 — 您必须给出适当的署名，提供指向本许可协议的链接，同时标明是否（对原始作品）作了修改。您可以用任何合理的方式来署名，但是不得以任何方式暗示许可人为您或您的使用背书。
>     非商业性使用 — 您不得将本作品用于商业目的。
>     相同方式共享 — 如果您再混合、转换或者基于本作品进行创作，您必须基于与原先许可协议相同的许可协议 分发您贡献的作品。
>     没有附加限制 — 您不得适用法律术语或者 技术措施 从而限制其他人做许可协议允许的事情。

请问能否遵守CC协议对来源进行标注并在Github和Curse上使用与简体中文包相同的协议呢？

**Comment by chesterccj305** [comment]
可以 沒問題
我應該再哪裡附加什麼嗎？

**Comment by sandtechnology** [comment]
仓库和Curse项目采用相同协议之后

在这个仓库的README.md和Curse项目介绍页附加上：
> 在[ 知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 之下基于[简体中文包](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package)繁化

类似的标注就可以了
再次感谢你的贡献！

**Comment by chesterccj305** [comment]
補上了 非常感謝

**Comment by sunnyayyl** [comment]
我覺得如果用 LICENSE.md 會比較好 https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
