### ISSUE TITLE
如果模組已有內建繁體中文，如何處理？

### ISSUE THREAD

**Issue by zica87** [chesterccj305/Mods-zh_tw-Lang-Pack#15]
例如botania。

**Comment by chesterccj305** [comment]
如果繁體中文和英文文本附合
原則上是不用處理的
若有缺行 就有需補上了翻譯

**Comment by chesterccj305** [comment]
補上的翻譯
為了配合原英文版
都是全數補上的

**Comment by zica87** [comment]
我是怕模組內建的優質翻譯 被此資源包的未查核的劣質翻譯取代掉。

**Comment by NatsuArashi** [comment]
原則上資源包會覆蓋在原有的條目上，資源包沒收錄的條目則會使用原本內建的中文。
簡單說就是無所謂

**Comment by zica87** [comment]
我是怕模組內建的優質翻譯會被未查核的劣質翻譯蓋掉...

**Comment by NatsuArashi** [comment]
你可以手動修改botania的內建翻譯
作者有開放編輯 
去找吧

**Comment by chesterccj305** [comment]
怕被為未查核翻譯蓋掉就 查核吧!!
我有時間也會做查核的工作
但有翻譯的真的太少了
