### ISSUE TITLE
是否開設翻譯社群討論站?

### ISSUE THREAD

**Issue by SiongSng** [chesterccj305/Mods-zh_tw-Lang-Pack#212]
想請問一下有沒有打算開設一個社群專門討論翻譯事務的?

因為我覺得有許多模組的翻譯有互相連通，經過我測試翻譯如果不同會導致遊玩時的敘述翻譯跟物品翻譯不同，導致如果要在JEI中搜尋物品可能會搜尋不到，所以我覺得可以使用一個翻譯網站 crowdin 他有很多專門用來翻譯的功能，github可以當作審核翻譯的地方跟放置原始碼，還有是否考慮使用Discord伺服器或者其他社群軟體方便大家討論翻譯文本。

如果覺得不需要也沒關係w     拍片很辛苦，很少創作者會去翻譯自己遊玩的遊戲，非常厲害，加油!!!

**Comment by chesterccj305** [comment]
目前還是傾向繼續在這使用
這裡的使用門檻已經很高了
會來討論投翻譯的人也不會很多啦
如果遊玩時有發現 問題 也可以在這提出
有統一的翻譯名稱 可以寫到wiki去
Discord之後考慮看看

**Comment by SiongSng** [comment]
ok，感謝回覆。
