### ISSUE TITLE
使用github actions自動發布資源包?

### ISSUE THREAD

**Issue by SiongSng** [chesterccj305/Mods-zh_tw-Lang-Pack#216]
你覺得需不需要Github裡面有一個功能叫做Actions，可以自動完成一些事情。
我剛剛寫了一個腳本檔案 讓他可以偵測到資源包資料有變動時，就會自動打包資源包，並且進行上傳到Github的Releases。
方便給有些人需要最新版本的資源包，又可以不用自己下載來壓縮，也可以節省發布到curseforge上的時間。
例如說每50個版本就發布一次到curseforge如果需要最新的就可以到Github的Releases來下載 你覺得如何呢?

實際測試結果:
![圖片](https://user-images.githubusercontent.com/48402225/108312951-6aa2a380-71f2-11eb-8003-8bdf7b4ee0a5.png)
   
可以直接下載打包後的檔案:
![圖片](https://user-images.githubusercontent.com/48402225/108313006-827a2780-71f2-11eb-8797-ee930911f17e.png)

如果這樣覺得可以，就可以接受 #217 的提交  接受之後這個腳本就會依據上述所說的功能生效
如果使用該功能 建議可以在 curseforge 使用此網址就可以前往最新版本的資源包下載位置了。
https://github.com/chesterccj305/Mods-zh_tw-Lang-Pack/releases/latest

不好意思 本文較長 需要花比較多時間閱讀

**Comment by chesterccj305** [comment]
我同意變更#217之後有需要做什麼嗎？

**Comment by SiongSng** [comment]
不用喔www 你現在到 [這裡](https://github.com/chesterccj305/Mods-zh_tw-Lang-Pack/releases/latest) 應該會發現多出一個版本惹
每次當有 `commits`  到 `main` 分支時，就會自動Build(自動產生資源包檔案，至於發布新版本時，會有一個描述內容，如果需要改的話，我也可以幫忙w
