### ISSUE TITLE
原版物品翻譯問題

### ISSUE THREAD

**Issue by EvanHsieh0415** [chesterccj305/Mods-zh_tw-Lang-Pack#223]
然測試的版本 : 1.12.2 無模組板

有些物品被翻譯得很奇怪

例如 :
> 岩漿塊 -> 岩漿水
> TNT -> 火藥爆炸

建議可以取消原版的翻譯

聯絡我: Discord `YT Mango #4092`

**Comment by EvanHsieh0415** [comment]
然後我測試的版本是1.12.2 無模組板

**Comment by EvanHsieh0415** [comment]
目前查到的翻譯問題位置有

|正確名稱|錯誤名稱|位置|備註|
|-|-|-|-|
|岩漿塊|岩漿水|1.12.2/assets/extraplanets/lang/zh_tw.lang `1436行`|應該是翻譯融化的岩漿塊時誤翻|
|TNT|火藥爆炸|1.12.2/assets/valoegheses_be/lang/zh_tw.lang `106行`|無|
|XX鐵軌(加速 感應 觸發)|XX軌道(助推 檢測 啟用)|1.12.2/assets/railcraft/lang/zh_tw.lang `1436-1439行`|火車模組誤翻|
|XX馬鎧|XX寵物盔甲|1.12.2/assets/lycanitesmobs/lang/zh_tw.lang `54-56行`|騎乘物盔甲翻譯問題|

**Comment by chesterccj305** [comment]
這種可以直接修改提交給我
我一定會給過的
1.12版本的 因為大量引用簡體中文翻譯轉繁體中文
所以存在一定的錯誤

**Comment by chesterccj305** [comment]
提供的四個 我已經修正了喔

**Comment by EvanHsieh0415** [comment]
OK 那我就關起來囉
