### ISSUE TITLE
建議改用LICENSE.md

### ISSUE THREAD

**Issue by sunnyayyl** [chesterccj305/Mods-zh_tw-Lang-Pack#230]
#1 
我覺得如果用 LICENSE.md 會比較好 https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
謝謝

**Comment by chesterccj305** [comment]
是要開放許可嗎？
還是引用許可
對不起 我有點不太懂

**Comment by sunnyayyl** [comment]
https://choosealicense.com/
這個會不會有幫助？

**Comment by sunnyayyl** [comment]
兩個都是,前面放開放許可，並在後面放引用許可

**Comment by sunnyayyl** [comment]
Copyright for portions of project [project name] are held by [original author, year] as part of project [their project] . All other copyright for project [project name] are held by [your name, year].
