### ISSUE TITLE
聊聊是否能與RPMTW合作?

### ISSUE THREAD

**Issue by SiongSng** [chesterccj305/Mods-zh_tw-Lang-Pack#246]
* RPMTW是指: https://www.rpmtw.ga
## **想聽聽看舞秋風與其他人的意見**

**Comment by chesterccj305** [comment]
我很樂意 要如何合作？

**Comment by sunnyayyl** [comment]
之前翻譯的內容需要重做嗎？ 還是可以將其上傳到新的？謝謝

**Comment by SiongSng** [comment]
不須重做  會上傳到新的 詳細請前往RPMTW官方Discord (https://discord.gg/5xApZtgV2u)
