### ISSUE TITLE
請問可以把1.15.2放到另一個分支(barnch)嗎?

### ISSUE THREAD

**Issue by yappy2000d** [chesterccj305/Mods-zh_tw-Lang-Pack#47]
這樣就可以方便的發布1.15.2的版本。並且在提交的時候也會比較方便跟使環境乾淨。
像[這樣](https://github.com/chesterccj305/Mods-zh_tw-Lang-Pack/pull/48)我在你這裡建立了一個PR
我把做起來的感覺給你看[[連接]](https://github.com/yappy2000d/Mods-zh_tw-Lang-Pack/tree/1.15.2)
在<>code的地方有一個Branch的選單可以切換版本。

**Comment by chesterccj305** [comment]
主要是怕 從curseforge過來的人找不太到
我會好好考慮一下這個做法的 謝謝指點

**Comment by yappy2000d** [comment]
現在醬好像更棒!更直觀了!謝謝秋風~:blush:
