### ISSUE TITLE
檔案位址問題

### ISSUE THREAD

**Issue by Nanamiya738** [chesterccj305/Mods-zh_tw-Lang-Pack#84]
秋風請問一下，假如一個模組在另一個模組新增了內容(例如匠魂副署添加新武器給匠魂寶典)
那我該把這個新翻譯建在匠魂的book，還是那個副署模組的？

**Comment by chesterccj305** [comment]
看原檔寫在哪就放哪喔

**Comment by chesterccj305** [comment]
像是匠魂副署寫在匠魂資料夾裡，就要去修改匠魂資料夾裡的內容
