### ISSUE TITLE
InventoryPets文件物件key值打錯的問題

### ISSUE THREAD

**Issue by kingdom84521** [chesterccj305/Mods-zh_tw-Lang-Pack#87]
如題，我已經找到錯在哪裡了
我在玩FTB Sky Odyssey的時候注意到的
./zh_tw-Lang-Pack-1.12v14/assets/inventorypets/lang/zh_tw.lang: Line 200

inventorypets.update.download=["Click to: [",{"text":"下載","color":"gold","hoverEvent":{"action":"show_text","value":{" text":"點擊這里以看現有最新的1.10版本下載","color":"gold"}},"clickEvent":{"action":"open_url","value":"http://minecraft .curseforge.com/projects/inventory-pets/files"}},"]"]

"value":{" text":"點擊這里以看現有最新的1.10版本下載","color":"gold"}} <- text的前面多了一個空格
正確應該為

inventorypets.update.download=["Click to: [",{"text":"下載","color":"gold","hoverEvent":{"action":"show_text","value":{"text":"點擊這里以看現有最新的1.10版本下載","color":"gold"}},"clickEvent":{"action":"open_url","value":"http://minecraft .curseforge.com/projects/inventory-pets/files"}},"]"]

這邊也留一份修正後測試過確定OK的檔案，麻煩協助修正
[zh_tw-Lang-Pack-1.12v14.zip](https://github.com/chesterccj305/Mods-zh_tw-Lang-Pack/files/5199530/zh_tw-Lang-Pack-1.12v14.zip)

**Comment by chesterccj305** [comment]
感謝告之
其實可以去內文直接提交修改
不用傳整份文檔喔
